services:
  db:
    image: mariadb:10.11
    restart: always
    network_mode: host
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    env_file:
      - .env
    depends_on:
      - db

  shortlink:
    build:
      context: ./shortlink-service
      dockerfile: Dockerfile
    network_mode: host
    env_file:
      - .env
    depends_on:
      - db
    
volumes:
  mariadb_data:
